config/routes.rb
Caball::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  root :to => 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :after_signup
  resources :accounts
  resources :milestones
  resources :disputes

  devise_for :filmmakers, :controllers => { :omniauth_callbacks => "filmmakers/omniauth_callbacks",:registrations => "filmmakers/registrations" , :sessions => "filmmakers/sessions" }
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations", :sessions => "users/sessions"}
  devise_for :clients#, :controllers => { :omniauth_callbacks => "clients/omniauth_callbacks", :registrations => "clients/registrations", :sessions => "clients/sessions"}

  # match '/filmmakers/sign_up'        => 'filmmakers#new', :user => { :meta_type => 'filmmaker' }
  match '/filmmakers'            => 'filmmakers#index'
  match '/filmmakers/dashboard'      => 'filmmakers/dashboard#index'
  match '/filmmakers/settings'       => 'filmmakers/dashboard#settings'
  match '/filmmakers/profile'        => 'filmmakers/profile#index'
  match '/filmmakers/accounts'       => 'filmmakers/accounts#index'
  match '/filmmakers/projects'       => 'filmmakers/projects#index'

  match '/accept_proposal/:proposal_id' => 'filmmakers/projects#accept_updated_proposal', :as => 'filmmaker_accept_project_proposal'
  match '/decline_proposal/:proposal_id' => 'filmmakers/projects#decline_updated_proposal', :as => 'filmmaker_decline_project_proposal'
  match '/edit_updated_proposal/:proposal_id' => 'filmmakers/projects#edit_updated_proposal', :as => 'filmmaker_edit_project_proposal'

	match '/filmmakers/:project_id/feedback' => 'filmmakers/feedback#index', :as => 'feedback_filmmaker_project'
  match '/clients/:project_id/feedback/:filmmaker_id'    => 'filmmakers/feedback#index', :as => 'feedback_client_project'

  match '/filmmakers/messages'       => 'filmmakers/conversations#index'
  match '/filmmakers/messages/new'   => 'filmmakers/conversations#create'
  get '/filmmakers/messages/:id/trash'   => 'filmmakers/conversations#trash', :as => 'filmmaker_message_trash'
  get '/filmmakers/messages/:id/untrash'   => 'filmmakers/conversations#untrash', :as => 'filmmaker_message_untrash'
  get '/filmmakers/messages/:id'   => 'filmmakers/conversations#show', :as => 'filmmaker_message'
  match '/filmmakers/messages/:id/reply' => 'filmmakers/conversations#reply', :as => 'filmmaker_message_reply'

  match '/filmmakers/disputes'       => 'disputes#index'
  match '/filmmakers/disputedetails' => 'disputes#disputedetails'
  match '/filmmakers/filmmaker-selection' => 'filmmakers/profile#filmmaker-selection'
  match '/filmmakers/portfolio'      => 'filmmakers/after_signup#portfolio'
  match '/filmmakers/blacklist_project' => 'filmmakers/dashboard#blacklist_project'
  match '/filmmakers/switch_pro'				 => 'filmmakers/dashboard#switch_pro'
  match '/fimmakers/submit_proposal'		=> 'filmmakers#submit_proposal', :as => 'submit_proposal'
 # match '/fimmakers/modify_project_proposal'		=> 'filmmakers#modify_project_proposal', :as => 'modify_project_proposal'
  match '/filmmakers/submit_feedback'   => 'filmmakers/feedback#submit_feedback', :as => 'submit_feedback'
  match '/filmmakers/milestones'     => 'milestones#show'
  match '/filmmakers/search'          => 'filmmakers#index', :as => :filmmaker_search
  match 'filmmakers/search_messages' => 'filmmakers#search_messages', :as => 'filmmaker_messages_search'
  match '/filmmakers/hire'           => 'filmmakers/profile#filmmaker_selection', :as => :filmmaker_selection
  match '/filmmakers/change_password' => 'filmmakers/dashboard#change_password'
  match '/filmmakers/change_email'   => 'filmmakers/dashboard#change_email'
  match '/filmmakers/change_email_settings' => 'filmmakers/dashboard#change_email_settings'
  match '/filmmakers/change_company_settings' => 'filmmakers/dashboard#change_company_settings'
  match '/filmmakers/upgrade'				 => 'filmmakers/dashboard#upgrade'

  match '/clients/create_direct_hire_proposal' => 'clients#create_direct_hire_proposal', :as => 'direct_hire_proposal'

  # match '/clients/sign_up'           => 'clients#new', :user => { :meta_type => 'client' }
  match '/clients/search_messages'   => 'clients#search_messages', :as => 'client_messages_search'
  get   '/clients/sign_in'           => 'clients/sessions#new'
  match '/clients/step_1'            => 'clients#step_1'
  match '/clients/step_2'            => 'clients#step_2'
  match '/clients/step_3'            => 'clients#step_3'
  match '/clients/dashboard'         => 'clients/dashboard#index'
  match '/clients/profile'           => 'clients/profile#index'
  match '/clients/accounts'          => 'clients/accounts#index'
  match '/clients/projects'          => 'clients/projects#index'
  match '/clients/settings'          => 'clients/dashboard#settings'
  match '/clients/messages'          => 'clients/conversations#index'
  match '/clients/messages/new'      => 'clients/conversations#create'
  get '/clients/messages/:id/trash'   => 'clients/conversations#trash', :as => 'client_message_trash'
  get '/clients/messages/:id/untrash'   => 'clients/conversations#untrash', :as => 'client_message_untrash'
  post '/clients/messages/:id/reply'   => 'clients/conversations#reply', :as => 'client_message_reply'
  get '/clients/messages/:id/delete_permanently'   => 'clients/conversations#delete_permanently', :as => 'client_message_delete_permanently'
  get '/clients/message/:message_id' => 'clients/conversations#show', :as => 'client_message_show'
  match '/clients/disputes'          => 'disputes#index'
  match '/clients/create-project'    => 'clients/dashboard#create_project'
  match '/clients/disputedetails'    => 'disputes#disputedetails'
  match '/clients/switch_pro'				 => 'clients/dashboard#switch_pro'
  match '/clients/release_payment'   => 'clients/projects#release_payment'
  match '/clients/milestones'        => 'milestones#index'
  match '/escrow/:milestone_id'      => 'clients/projects#escrow_milestone_funds', :as => :escrow
  match '/clients/download_proposal_attachment/:proposal_id' => 'clients/projects#download_attachment', :as => 'download_proposal_attachment'
  match '/auth/:provider/callback'   => 'clients/sessions#create'

  match '/clients/add-bank-account'    => 'clients/accounts#add_bank_account'
  match '/clients/add-credit-card'    => 'clients/accounts#add_credit_card'
  match '/clients/create_bank_account' => 'clients/accounts#create_balanced_bank_account'
  match '/clients/create_credit_card' => 'clients/accounts#create_balanced_credit_card'

  match '/filmmakers/add-bank-account'    => 'filmmakers/accounts#add_bank_account'
  match '/filmmakers/add-credit-card'    => 'filmmakers/accounts#add_credit_card'
  match '/filmmakers/create_bank_account' => 'filmmakers/accounts#create_balanced_bank_account'
  match '/filmmakers/create_credit_card' => 'filmmakers/accounts#create_balanced_credit_card'


  match '/clients/change_password'   => 'clients/dashboard#change_password'
  match '/clients/change_email'      => 'clients/dashboard#change_email'
  match '/clients/change_email_settings' => 'clients/dashboard#change_email_settings'

  get "activities/index"

  match '/users/select_user' => 'static_pages#select_user'
  match '/our_team' => 'static_pages#team'
  match '/our_mission' => 'static_pages#mission'
  match '/about' => 'static_pages#about_us'
  match '/contact' => 'contact_us/contacts#new'
  match '/contact_us' => 'contact_us/contacts#new'
  match '/faq' => 'static_pages#faq'
  match '/FAQ' => 'static_pages#faq'

  # get 'people', to: 'users#index', via: :all
  resources :users, :path => "people"

  match '/people/:id' => 'filmmakers#update', :via => 'post'
  #match "/blog(/*path)" => redirect{ |env, req| "http://blog.filmzu.com" + (req.path ? "#{req.path}" : '/')}

  match 'check_url_param' => 'application#check_url_param'

  match "/main_search" => 'application#main_search'

  match 'users/recommended_projects' => 'users#next_recommended_projects'
  match 'users/recommended_people' => 'users#next_recommended_people'
  match 'users/recommended_events' => 'users#next_recommended_events'

  match '/users/set_notification_check_time' => 'users#set_notification_check_time'

  match '/users/update' => 'users#custom_update', :via => 'POST'
  match '/users/step_1' => 'users#step_1'

  match '/users/step_1_reload' => 'users#step_1_reload'
  match '/users/step_2' => 'users#step_2'
  match '/users/step_3' => 'users#step_3'
  match '/users/files_upload' => 'users#files_upload'
  match '/users/agent_names' => 'users#agent_names'
  match '/users/profile' => 'users#profile'
  match '/users/change_password' => 'users#change_password'
  match '/users/change_email' => 'users#change_email'
  match '/users/change_email_settings' => 'users#change_email_settings'
  get '/users/search_by_name'

  match '/events/files_upload' => 'events#files_upload'
  match '/projects/files_upload' => 'projects#files_upload'
  match '/comments/files_upload' => 'comments#files_upload'
  #match '/blogs/files_upload' => 'blogs#files_upload'
  match '/projects/modify_project_proposal'		=> 'projects#modify_project_proposal', :as => 'modify_project_proposal'

   resources :filmmakers do
     resources :conversations , :photos
   end

   resources :clients do
     resources :conversations , :photos
   end

  resources :users do
    resources :characteristics, :photos, :talents, :profile#, :blogs
  end


  match '/roles/destroy' => 'roles#destroy', :via => 'POST'


  match '/projects/step_1'          => 'projects#step_1'
  match '/projects/step_2'          => 'projects#step_2'
  match '/projects/step_3'          => 'projects#step_3'
  match '/projects/add_filled_role' => 'projects#add_filled_role'
	match '/projects/view/:project_id'	=> 'projects#view_project', :as => 'view_project'

app/controllers/clients/dashboard_controller.rb
class Clients::DashboardController < ApplicationController

  before_filter :authenticate_client!
	layout 'application'
	#before_filter :create_lazy_project, :only => 'index'
  before_filter :create_lproject_from_session, only: 'index'

  def index
    client = current_client
    @projects = client.recent_projects(params)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  def create_project
    render :layout => 'popup'
  end

  def create_lproject_from_session
    lazy = session[:lazy]
    project_id = session[:project_id]
    is_featured = session[:featured]
    session[:lazy_featured_project] = true if ['true', true].include?(is_featured)
    if project_id.present?
      project = Project.where('ip_address=? AND user_id IS NULL', request.remote_ip).last
      return if project.blank?
      project.update_attributes(:user_id => current_client.id)
      [:lazy, :project_id, :featured].each do |ss|
        session[ss] = nil
      end
      p "=BEFORE JOB STARTED="
      BalancedJob.new.async.create_marketplace_customer(current_client)
      p "=AFTER JOB COMPLETION="
      ProjectMailer.delay.project_confirmation(project)
      p "=MAILER PROJECT SENT="
    end
  end

	def create_lazy_project
	  if request.referer.present?
  		referer = request.referer.split("&")
  		prj_id=0
  		session[:lazy_featured_project] = true if referer.last.include?('featured')
  		if (referer.last.to_s.include?('prj') || referer[-2].to_s.include?('prj'))
  			project = Project.where("ip_address = ? and user_id IS NULL", request.remote_ip).last
  			return if project.nil?
  			project.update_attributes(:user_id => current_client.id)
  			prj_id= referer.select{|e| e if e.include? 'prj'}.first.split("=").last.to_i
  			p "=BEFORE JOB STARTED="
  			BalancedJob.new.async.create_marketplace_customer(current_client)
  			p "=AFTER JOB COMPLETION="
  		end
  		redirect_to '/clients/accounts?prj='+prj_id.to_s if session.has_key?(:lazy_featured_project)
	  end
	end

	def switch_pro
		if request.get?
			@client = current_client
		elsif request.post?
			client = current_client
			pro_account = client.pro_account
			if pro_account
				current_client.pro_account.update_attributes(:account_type => params[:account_type])
				client_credit_card = Balanced::Card.fetch(current_client.credit_cards.last.credit_card_uri)
				client_credit_card.debit(
          :amount => 9,
					:description => 'Your account is upgraded now!'
			  )
			else
				current_client.pro_account.create(:account_type => params[:account_type])
			end
			redirect_to '/clients/dashboard'
		end
	end
end

app/controllers/clients/profile_controller.rb
class Clients::ProfileController < ApplicationController

  before_filter :authenticate_client!, :except => [:show]

  def index
    @client = current_client
    @feedback_projects = ProjectFeedback.filmamker_feedback_projects(current_client)
    @projects = @client.projects
    @client_feedbacks = @client.project_feedbacks
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end
  
  def show
    @client = Client.find(params[:id])
  end
  
  
end

app/controllers/clients/registrations_controller.rb
class Clients::RegistrationsController < Devise::RegistrationsController

  # load_and_authorize_resource :except => [:new]
 
  def new
      
      
      @client = Client.new
      @client.save
 #     @user.add_meta :user_client
   end
  
  def create
      
    build_resource(params[:client])

    if resource.save
				# create registered filmmaker a marketplace customer
	
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        redirect_back_or(edit_user_path(resource))
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  def after_sign_up_path_for(resource)
    
    '/clients/dashboard'
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
  def authenticate_client!
    authenticate_user!
    unless current_user.type == "Client"
      redirect_to "/", :alert => "You need to be signed in as Client to see this page"
    end
  end

  def is_active(navigation_link)
    (request.original_url == navigation_link) ? 'active' : ''
  end

  def display_project_feedback_filmmaker(project)
    project_proposals = project.project_proposals
    dr_project_proposals = project.direct_hire_proposals
    proposal = project.project_proposals.blank? ? dr_project_proposals.where("filmmaker_id = ?",current_filmmaker.id) : project.project_proposals.where("filmmaker_id = ?",current_filmmaker.id)
    ProjectFeedback.where("project_id = ? AND filmmaker_id = ?",project.id,current_filmmaker.id).first.blank? && proposal.first.try(:is_approved)
  end

  def display_project_feedback_client(project)
    project.client == current_client && FilmmakerFeedback.where(:project_id => project.id, :client_id => current_client.id).blank?
  end

  def star_rating(client_feedbacks)
    unless client_feedbacks.blank?
      sum = ( ( ( client_feedbacks.collect(&:total_rating).sum.to_f / (25 * client_feedbacks.count).to_f ) ) * 5.0).round
    else
      sum = 0
    end
    "star-#{sum}.png"
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

	def file_name(upload)
   (upload.attachment? && upload.attachment.file.present?) ? upload.attachment.file.filename : "Attachment"
	end

  def display_proposal_button(project)
    display = false
    proposal_submitted = project.project_proposals.where("filmmaker_id = ?",current_filmmaker.id)
    time_left = ((((project.created_at + project.project_details.second.split(" ").first.to_i.days) - Time.now).to_i) / 3600 ) rescue 0
    location_preference = project.location.blank? ? true : project.location == current_filmmaker.location
    #project_skills = project.skills.split(",").map(&:downcase) rescue []
    filmmaker_skills = current_filmmaker.skills.split(",").map(&:downcase) rescue []
    #skills_preference = project_skills.empty? ? true : (project_skills - filmmaker_skills).empty?
    #if (proposal_submitted.empty?) && !(project.as_hire?) && (location_preference) && (time_left != 0)# && (skills_preference)
    if (proposal_submitted.empty?) && (time_left != 0) #&& !(project.as_hire?)
      display = true
    end
    [display,!(proposal_submitted.empty?)]
  end

  def project_rating(project_feedbacks)
    unless project_feedbacks.blank?
      sum = ( ( ( project_feedbacks.collect(&:total_rating).sum.to_f / (25 * project_feedbacks.count).to_f ) ) * 5.0).round 
    else
      sum = 0
    end
    sum
  end  

  def days_left(count)
    if (count < 0)
      "<span>Closed</span>"
    else
      "<span>#{count} d</span> Left"
    end
  end  

  def display_feedback_button(project)
    FilmmakerFeedback.where("project_id = ? AND client_id = ?",project.id,current_client.id).first.blank? && !(current_client.projects.where("id = ?",project.id).first.blank?)
  end  

end

app/views/clients/projects/_proposals_listing.html.erb
<% proposals.each do |proposal| %>
  <li>
    <%= render :partial => 'proposal', :locals => {:proposal => proposal} %>
  </li>
<% end %>

app/views/clients/projects/accept_project_proposal.js.erb
$('.email-detail-box').html("<%= escape_javascript(render :partial => 'clients/conversations/detail_box', :locals => {:conversation => @conversation})%>");

app/views/clients/projects/decline_project_proposal.js.erb
$('.email-detail-box').html("<%= escape_javascript(render :partial => 'clients/conversations/detail_box', :locals => {:conversation => @conversation})%>");

app/views/clients/projects/escrow_milestone_funds.js.erb
$('#cboxClose').trigger('click');

app/views/clients/projects/hire_filmmaker.html.erb
<div class="dialog-box fun-popup">
  <div class="conf-hpart">
    <h2>Hire Filmmaker</h2>
  </div>
  <p>Filmmaker hired successfully</p>
	<p><%= link_to 'Fund your account and get started!', clients_accounts_path %></p>
</div>

<script type="text/javascript">
  var proposal_id = <%= @proposal.id %>
  $(".proposal-action-buttons-" + proposal_id).hide();
</script>

app/views/clients/projects/index.js.erb
$("#search_proposal_form").val("");
$(".proposal-count").html("<%= @proposals.size %>")
$('.prj-listing').html("<%= escape_javascript(render :partial => 'proposals_listing', :locals => {:proposals => @proposals})%>");

app/views/clients/projects/release_direct_hire_payment.html.erb
<div class="dialog-box fun-popup">
  <div class="conf-hpart">
	  <h2>Escrow Funding and Payments</h2>
  </div>
  <div class="filmaker-box clearfix">
  	<div class="film-img-box fl">
      <%= image_tag @filmmaker.profile_photo, :width => 100, :height => 100 %>
    </div>
    <div class="film-cpart">
    	<h3><%= @filmmaker.name %></h3>
      <p>Desired Rate: <span>$<%= @filmmaker.rate%>/day</span></p>
      <ul class="status-box clearfix">
      	<li>
          <%= image_tag('blank-img.png', class: 'red-loc-icon') %><%=@filmmaker.location%>
        </li>
        <li>
          <%= image_tag('blank-img.png', class: 'red-star-icon') %>
          <%= @filmmaker.filmmaker_feedbacks.any? ? @filmmaker.filmmaker_feedbacks.average(:rating).to_i : 0 %> stars
        </li>
      </ul>
    </div>
  </div>
  <div class="funding-form clearfix">
  	<div class="fun-box1 fl">
    	<div class="colum1 fl">
      	<label class='ml10'>Payment Milestones
          <a class="help-link" href="#">
            <%= image_tag('blank-img.png', class: 'quation-icon') %>
          </a>
        </label>
        <% @milestones.each do |milestone| %>
			    <input type="text" class="int188 mt7" value="<%= milestone.name%>" />
        <% end %>
      </div>
      <div class="colum2 fl">
      	<label class='ml10'>Delivery Date</label>
        <% @milestones.each do |milestone| %>
			    <input type="text" class="int96 mt7" value="<%=milestone.delivery_date %>" />
        <% end %>
        <div class="total-text">Total</div>
      </div>
      <div class="colum3 fl">
      	<label class='ml10'>Amount</label>
        <% @milestones.each do |milestone| %>
			    <input type="text" class="int96 mt7" value="<%=milestone.amount %>" />
        <% end %>
	      <input type="text" class="int96 mt7" value=<%= @direct_hire_proposal.direct_hire_proposal_milestones.sum(:amount) %> />
      </div>
    </div>
    <div class="fun-box2 fl">
    	<div class="colum1 fl">
      	<label class='mb10'>Fund Escrow</label>
        <% @milestones.each do |milestone| %>
			    <% if milestone.fund_escrowed %>
			      <div class="icon-int clearfix mt5" style="margin-bottom:5px;">
              <%= image_tag('blank-img.png', class: 'blue-ok-icon') %>
              <input type="text" value="Funded" class="int96" />
            </div>
	        <% else %>
				    <%= link_to "Fund", client_fund_escrow_direct_hire_milestone_path(milestone), class: 'blue-btn mbtn5' %>
		      <% end %>
        <% end %>
      </div>
      <div class="colum2 fl">
      	<label>Release Escrow</label>
		    <% @milestones.each do |milestone| %>
			    <% if milestone.payment_released %>
			      <div class="icon-int clearfix mt5" style="width:112px;">
              <%= image_tag('blank-img.png', class: 'blue-ok-icon') %>
              <input type="text" value="$<%=milestone.pay_amount%>" class="int96" style="width: 66px !important;"/>
            </div>
	        <% else %>
			      <%= link_to "Release Payment", client_release_payment_direct_hire_milestone_path(milestone), class: 'blue-btn release-btn' %>
		      <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/clients/projects/release_payment.html.erb
<div class="dialog-box fun-popup">
  <div class="conf-hpart">
	  <h2>Escrow Funding and Payments</h2>
  </div>
  <div class="filmaker-box clearfix">
  	<div class="film-img-box fl">
      <%= image_tag @filmmaker.profile_photo, :width => 100, :height => 100 %>
    </div>
    <div class="film-cpart">
    	<h3><%= @filmmaker.name %></h3>
      <p>Desired Rate: <span>$<%= @filmmaker.rate%>/day</span></p>
      <ul class="status-box clearfix">
      	<li>
          <%= image_tag('blank-img.png', class: 'red-loc-icon') %><%=@filmmaker.location%>
        </li>
        <li>
          <%= image_tag('blank-img.png', class: 'red-star-icon') %>
          <%= @filmmaker.filmmaker_feedbacks.any? ? @filmmaker.filmmaker_feedbacks.average(:rating).to_i : 0 %> stars
        </li>
      </ul>
    </div>
  </div>
  <div class="funding-form clearfix">
  	<div class="fun-box1 fl">
    	<div class="colum1 fl">
      	<label class='ml10'>Payment Milestones
          <a class="help-link" href="#">
            <%= image_tag('blank-img.png', class: 'quation-icon') %>
          </a>
        </label>
        <% if @updated_milestones.present? %>
          <% @updated_milestones.each do |updated_milestone| %>
            <input type="text" class="int188 mt7" value="<%= updated_milestone.name%>" />
          <% end %>
        <% else %>
          <% @milestones.each do |milestone| %>
  			    <input type="text" class="int188 mt7" value="<%= milestone.name%>" />
          <% end %>
        <% end %>
      </div>
      <div class="colum2 fl">
      	<label class='ml10'>Delivery Date</label>
        <% if @updated_milestones.present? %>
          <% @updated_milestones.each do |updated_milestone| %>
            <input type="text" class="int96 mt7" value="<%= updated_milestone.delivery_date %>" />
          <% end %>
        <% else %>
          <% @milestones.each do |milestone| %>
  			    <input type="text" class="int96 mt7" value="<%=milestone.delivery_date %>" />
          <% end %>
        <% end %>
        <div class="total-text">Total</div>
      </div>
      <div class="colum3 fl">
      	<label class='ml10'>Amount</label>
        <% if @updated_milestones.present? %>
          <% @updated_milestones.each do |updated_milestone| %>
            <input type="text" class="int96 mt7" value="<%= updated_milestone.amount %>" />
          <% end %>
          <input type="text" class="int96 mt7" value=<%= @updated_milestones.sum(:amount) %> />
        <% else %>
          <% @milestones.each do |milestone| %>
            <input type="text" class="int96 mt7" value="<%= milestone.amount %>" />
          <% end %>
          <input type="text" class="int96 mt7" value=<%= @milestones.sum(:amount) %> />
        <% end %>
      </div>
    </div>
    <div class="fun-box2 fl">
    	<div class="colum1 fl">
      	<label class='mb10'>Fund Escrow</label>
        <% if @updated_milestones.present? %>
          <% @updated_milestones.each do |milestone| %>
            <% if milestone.fund_escrowed %>
              <div class="icon-int clearfix mt5">
                <%= image_tag('blank-img.png', class: 'blue-ok-icon') %>
                <input type="text" value="Funded" class="int96" />
              </div>
            <% else %>
              <%= link_to "Fund", client_fund_escrow_updated_milestone_path(milestone), class: 'blue-btn' %>
            <% end %>
          <% end %>
        <% else %>
          <% @milestones.each do |milestone| %>
  			    <% if milestone.fund_escrowed %>
  			      <div class="icon-int clearfix mt5" style="margin-bottom:6px;">
                <%= image_tag('blank-img.png', class: 'blue-ok-icon') %>
                <input type="text" value="Funded" class="int96" />
              </div>
  	        <% else %>
  				    <%= link_to "Fund", escrow_path(milestone), class: 'blue-btn' %>
  		      <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="colum2 fl">
      	<label>Release Escrow</label>
        <% if @updated_milestones.present? %>
          <% @updated_milestones.each do |milestone| %>
            <% if milestone.payment_released %>
              <div class="icon-int clearfix mt5" style="width:112px;">
                <%= image_tag('blank-img.png', class: 'blue-ok-icon') %>
                <input type="text" value="$<%=milestone.pay_amount%>" class="int96" style="width: 66px !important;"/>
              </div>
            <% else %>
              <%= link_to "Release Payment", client_release_payment_updated_milestone_path(milestone), class: 'blue-btn release-btn' %>
            <% end %>
          <% end %>
        <% else %>
  		    <% @milestones.each do |milestone| %>
  			    <% if milestone.payment_released %>
  			      <div class="icon-int clearfix mt5" style="width:112px;">
                <%= image_tag('blank-img.png', class: 'blue-ok-icon') %>
                <input type="text" value="$<%=milestone.pay_amount%>" class="int96" style="width: 66px !important;"/>
              </div>
  	        <% else %>
  			      <%= link_to "Release Payment", escrow_path(milestone, action_type: 'release'), class: 'blue-btn release-btn' %>
  		      <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
$( "a.blue-btn.mt5" ).click(function() {
  $('a.blue-btn.mt5').hide();
});
$( "a.blue-btn.release-btn" ).click(function() {
  $('a.blue-btn.release-btn').hide();
});
</script>